# Generated by Django 2.1.1 on 2018-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181004_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='no_avatar.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
