# Generated by Django 2.1.2 on 2018-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181004_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Link',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
