# Generated by Django 2.1.1 on 2018-11-23 17:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181123_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_he',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10, verbose_name='status'),
        ),
    ]
