# Generated by Django 2.2 on 2019-04-04 11:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='body'),
        ),
    ]
